### ISSUE TITLE
Migrate Helm chart from EnterpriseDB organization

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/charts#1]
EDB had implemented a basic helm chart for Cloud Native PostgreSQL (the name of CloudNativePG before it was open sourced by EDB). It is available at https://github.com/EnterpriseDB/cloud-native-postgresql-helm

As part of the open source initiative, that Helm Chart should be moved in the CloudNativePG organization (https://github.com/cloudnative-pg/charts repository)

**Comment by phisco** [comment]
Migrated code as is directly to main (that was not intentional, I pushed the first branch and it became the default, so @sxd renamed it to main and set as default).
Still need to address the pipelines and release process though.

**Comment by sxd** [comment]
@phisco that makes sense to me, different tags with the chart name will make some kind of order.

**Comment by phisco** [comment]
I'll work on that in the next days💪
