### ISSUE TITLE
[Feature] include sample grafana dashboards / prometheus alerts in chart

### ISSUE THREAD

**Issue by jcpunk** [cloudnative-pg/charts#100]
Projects like `strimzi` and `cilium` are including optional grafana dashboards in their helm charts.  It would be nice if the cloudnative-pg chart also had the option of loading the example dashboard from  https://github.com/cloudnative-pg/cloudnative-pg/tree/main/docs/src/samples/monitoring

**Comment by itay-grudev** [comment]
Closing as completed. The operator chart adds a `ConfigMap` that loads the Grafana Dashboard if enabled:

```yaml
monitoring:
  grafanaDashboard:
    create: true
```

Alternatively you can take a look at [`cloudnative-pg/grafana-dashboards`](https://github.com/cloudnative-pg/grafana-dashboards/tree/main/charts/cluster) where our cluster dashboard is located.

It's also available on [grafana.com](https://grafana.com/grafana/dashboards/20417-cloudnativepg/)'s dashboard marketplace.
