### ISSUE TITLE
Cannot disable weak TLS ciphers

### ISSUE THREAD

**Issue by senyahnoj** [cloudnative-pg/charts#127]
It is becoming increasingly common security policy to disable weak ciphers in TLS (ref: https://support.securityscorecard.com/hc/en-us/articles/115003260246-TLS-Service-Supports-Weak-Cipher-Suite#:~:text=Ultimately%2C%20it%20is%20recommended%20to,discovered%20that%20render%20it%20insecure.)

The CNPG operator does not allow you to do this. 

We want to restrict TLS to only ECDHE-RSA-AES256-GCM-SHA384 and minimum TLS version to 1.2. Therefore, we added the following to our installation to set the ciphers for postgresql.conf

```yaml
postgresql:
  parameters:
     ssl_ciphers: ECDHE-RSA-AES256-GCM-SHA384
     ssl_min_protocol_version: TLSv1.2
```
Unfortunately, when you try and set these, the helm install fails with a message

`[spec.postgresql.parameters.ssl_ciphers: Invalid value: "ECDHE-RSA-AES256-GCM-SHA384": Can't set fixed configuration parameter, spec.postgresql.parameters.ssl_min_protocol_version: Invalid value: "TLSv1.2": Can't set fixed configuration parameter]`

Despite the operator letting you set spec.postgresql.parameters with key/value configuration options for postgresql.conf, there are some which the operator is intentionally locking down and this includes ones which would be needed for restricting the cipher suites.

https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/postgres/configuration.go#L284

Helm charts/operators for MySQL, MongoDB and Neo4j all allow the cipher lists to be restricted. The PostgreSQL implementation should seriously consider allowing the same.

**Comment by sxd** [comment]
HI @senyahnoj 

This is not the place to talk about this, probably you should open an issue discussion in github.com/cloudnative-pg/cloudnative-pg this project it's just for the helm charts

Regards

**Comment by senyahnoj** [comment]
Re-raised at https://github.com/cloudnative-pg/cloudnative-pg/issues/3376 as instructed
