### ISSUE TITLE
Installing via terraform

### ISSUE THREAD

**Issue by cristianrat** [cloudnative-pg/charts#145]
Hi,

Perhaps I am doing something wrong, but this isn't working right via terraform
```
resource "helm_release" "cloudnative_pg" {
  name             = "cnpg"
  namespace        = local.namespace
  create_namespace = true

  repository = "https://cloudnative-pg.github.io/charts"
  chart      = "cnpg/cloudnative-pg"
  version    = "0.18.2"  
}
```
The error is 
`Error: could not download chart: chart "cnpg/cloudnative-pg" version "0.18.2" not found in https://cloudnative-pg.github.io/charts repository`
I know this isn't terraform support, but I've not had this issue with other helm repos, where the chart name had a / and it didn't like that so I had to put in the repository url similar to this 
```
  repository = "https://cloudnative-pg.github.io/charts/cnpg/"
  chart      = "cloudnative-pg"
  version    = "0.18.2"
```
Which gives out a different error, `Error: could not download chart: Chart.yaml file is missing`

Has anybody installed this via terraform?

**Comment by labkey-stuartm** [comment]
Here is how we are using this in Terraform.  

```
resource "helm_release" "cloudnative_pg" {
  name             = module.eks_cluster.cluster_name
  chart            = "cloudnative-pg"
  repository       = "https://cloudnative-pg.github.io/charts"
  version          = "0.18.1"
  namespace        = "cnpg-system"
  create_namespace = true
  description      = "CloudNativePG Operator Helm chart deployment configuration"
```

Hope this helps

**Comment by cristianrat** [comment]
@labkey-stuartm Doesn't work for me
```
│ Error: could not download chart: Chart.yaml file is missing
│
│   with module.cloudnative_pg.helm_release.cloudnative_pg,
│   on cloudnative-pg/main.tf line 1, in resource "helm_release" "cloudnative_pg":
│    1: resource "helm_release" "cloudnative_pg" 
```
Now, it might be because I am on windows wsl2, so gonna try it via gh actions
This is my tf
```
resource "helm_release" "cloudnative_pg" {
  name             = "cnpg"
  namespace        = "cnpg-system"
  create_namespace = true

  repository  = "https://cloudnative-pg.github.io/charts"
  chart       = "cloudnative-pg"
  version     = "0.18.1"
  description = "CloudNativePG Operator Helm chart deployment configuration"  
}
```

**Comment by HendrikLevering** [comment]
It seems that the url redirects. Try this url for repository:
`https://cloudnative-pg.io/charts`

**Comment by cristianrat** [comment]
@HendrikLevering 
Doesn't make a difference
` Error: could not download chart: Chart.yaml file is missing`

**Comment by cristianrat** [comment]
funny how the most basic of things can't be done
but anyway, if anybody comes across this thread, there is another way in terraform to install a helm chart, by pointing directly to the archive file
something along the lines of
```
resource "helm_release" "cloudnative_pg" {
  name             = "cnpg" # what ever you want
  namespace        = "cnpg-system" # what ever you want
  create_namespace = true 
  chart            = "https://cloudnative-pg.github.io/charts/cloudnative-pg-0.19.1.tgz" # what ever you want, change version etc
  description      = "CloudNativePG Operator Helm chart deployment configuration"
  values           = [
    "${file("${path.module}/values.yaml")}" # if you want values
  ]
}

```

**Comment by phisco** [comment]
Feels more like an issue with the terraform provider 😅 our helm chart is simply hosted as a github page.

**Comment by cristianrat** [comment]
It could be @phisco 
I've had issues with other charts as well, had to try all sorts of weird combinations, like have "" for chart name and the full path in the repo, and so on
So... which ever
Wanted to help others, so I posted the above way that works

**Comment by phisco** [comment]
Sure, and thanks for that @cristianrat! I was referring to the issue per se, not your last comment! So it feels this issue could be closed, right?

**Comment by cristianrat** [comment]
👍 
Since it doesn't seem like we can do anything about it, then yes, we at least have a way forward
thanks for your hard work on this
It's greatly appreciated

**Comment by CoreFloDev** [comment]
Hi,

I had a similar issue when creating a helm chart dependency, I was able to fix it with:
```
dependencies:
  - name: cloudnative-pg
    version: 0.21.5
    repository: https://cloudnative-pg.io/charts
```

I think maybe it is not working for @cristianrat because the name isn't correct, any other name wasn't working for me

**Comment by cristianrat** [comment]
> Hi,
> 
> I had a similar issue when creating a helm chart dependency, I was able to fix it with:
> 
> ```
> dependencies:
>   - name: cloudnative-pg
>     version: 0.21.5
>     repository: https://cloudnative-pg.io/charts
> ```
> 
> I think maybe it is not working for @cristianrat because the name isn't correct, any other name wasn't working for me

is that a yaml manifest?
For me the issue was only with terraform, didn't really try with simple yaml :)
for me it's all TF
