### ISSUE TITLE
CRDs

### ISSUE THREAD

**Issue by andyli** [cloudnative-pg/charts#15]
I noticed that the CRDs of this helm chart are placed in the `templates` folder instead of the Helm 3 special `crds` folder. I wonder if this is intentional and will there be any gotchas when upgrading the helm release?

This is more of a question than a change request - I'm not familiar with the technical details of Helm. But I used several Helm charts that whenever a new version has changes to the CRDs, requires me to manually update the CRDs. e.g. https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-35x-to-36x

**Comment by toboshii** [comment]
There's a valid and quite common reason for needing this. When using GitOps tools like Flux or ArgoCD it's not uncommon to separate CRDs so they are are loaded before any other resources when bootstrapping into a clean cluster to prevent race conditions:
![race condition](https://user-images.githubusercontent.com/63410334/179018469-e4d58393-cced-43f8-9214-d61bbe44b782.png)
You can see an example of this [here](https://github.com/toboshii/home-ops/tree/main/cluster/crds), the CRD directory is loaded before anything else during a new cluster bootstrap.

If you won't/can't consider moving to the Helm3 CRD directory, please consider adding a chart value that disables the CRD templates, for example [cert-manager](https://github.com/cert-manager/cert-manager/blob/f109f34aee45f5c821e89bc4ff65edfe7bdea8be/deploy/charts/cert-manager/values.yaml#L44) or [Kyverno](https://github.com/kyverno/kyverno/blob/f6c131cfcceebb26bd49f831522a3d0269ce6068/charts/kyverno/values.yaml#L367)

**Comment by phisco** [comment]
I'll definitely add an option to disable crds through values, however This chart is deploying the operator itself, without using the crds directly, so it should not trigger any race condition. But I agree it doesn't cost much to add a value for that.
