### ISSUE TITLE
Can't override imageName in cluster to pull image from local registry instead of ghcr

### ISSUE THREAD

**Issue by lilambivert** [cloudnative-pg/charts#169]
I've set the imageName key in the spec setting to pull from my local registry as my kubernetes cluster doesn't have access to the internet. However, when I spin up the cloudnative-pg cluster the initdb pod tries to pull the image from ghcr.io/cloudnative-pg/postgresql instead of the value I've specified in imageName.

Is there a way to override this value so that the cluster can pull an image from a different source?

**Comment by lukastopiarz** [comment]
@lilambivert take a look at PG cluster CRD spec. You need to edit `imageName` spec field.
