### ISSUE TITLE
version well-know label is hardcoded to appVersion in Chart.yaml

### ISSUE THREAD

**Issue by nareshov** [cloudnative-pg/charts#173]
The intention seems to be that it should match what is set by `.Values.image.tag` else default to `.Chart.appVersion`.

This issue causes changes to the label even when `.Values.image.tag` is set ti an older value (as of 17th Jan 2024):

```diff
-    app.kubernetes.io/version: 1.20.2
-    helm.sh/chart: cloudnative-pg-0.18.2
+    app.kubernetes.io/version: 1.22.0
+    helm.sh/chart: cloudnative-pg-0.20.0
```

**Comment by phisco** [comment]
As stated [here](https://github.com/cloudnative-pg/charts/pull/174#issuecomment-1914988716), this is intended behavior.
