### ISSUE TITLE
Provide a Cluster chart

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/charts#178]
We have an operator chart, but we lack a chart that initializes a database cluster.

The objective of such a chart should not be to provide a straight through interface to a `Cluster.postgresql.cnpg.io` object. Advanced use should be done by interacting with CNPG's CRDs directly. Instead to the chart should provide a reliable, easy-to-use method for setting up a CNPG cluster and related resources with safe defaults. 

An good cluster chart should cover multiple aspects, such as:
* Provision a cluster
* Provision a Pooler
* Backup configuration
* Scheduled Backups
* Disaster recovery
* Alerting and Monitoring
* Safe and reliable defaults and warnings whenever user settings result in unsafe configuration
* Tests

**Comment by jwklijnsma** [comment]
This is nice one we made are own 8 months ago
