### ISSUE TITLE
Feature: Cluster Chart PrometheusRule alerts

### ISSUE THREAD

**Issue by itay-grudev** [cloudnative-pg/charts#192]
Automated alerts for cluster issues would be extremely useful to improve the safety of a CNPG cluster.

Ideally, alerts should come in both a `warning` and `critical` severity levels, so that users have time to react to an alert before a problem escalates.

Proposed alerts should include:

* Instance failure based on the cluster spec
* Low Disk space
* High Replication Lag
* High connection count on any instance

There are some alerts such as high CPU usage and/or memory that are already covered by `kube-prometheus-stack` and should not be implemented here.

**Comment by maxpain** [comment]
@itay-grudev could you also add PrometheusRule to the `cloudnative-pg` chart?

**Comment by itay-grudev** [comment]
@maxpain That makes sense. Can you create a new issue for that feature request? Please mention wWhat kind of alerts are you missing in addition to alerting if the operator deployment has no replicas.
