### ISSUE TITLE
Add support for existing backup credentials

### ISSUE THREAD

**Issue by donch** [cloudnative-pg/charts#197]
Currently, the *cluster* chart create a secret containing backup credentials like S3. 
There is no way to provide a existingSecret to avoid putting these credentials in the Helm Values.

**Comment by DASPRiD** [comment]
I was just about to set up my first cluster and ran into that problem as well. Since we are using GitOps, it's anything but ideal to store the secret access key straight in Git.

**Comment by mrclrchtr** [comment]
Same here. I can not store the secret in the values file.

**Comment by SalvoRusso8** [comment]
Hi all, any update about this feature?
I think is very important to permit the use of an existing secret to allow the use of this chart with tools like fluxcd

**Comment by itay-grudev** [comment]
@SalvoRusso8 There is PR that implements this: #239. Would you be able to test that and confirm it works?
