### ISSUE TITLE
Backups incompatibility with unencrypted minio

### ISSUE THREAD

**Issue by donch** [cloudnative-pg/charts#198]
When i enable S3 backups with a minio configuration.

The barmanConfig looks like : 

`  barmanObjectStore:
    wal:
      compression: gzip
      encryption: AES256
    data:
      compression: gzip
      encryption: AES256
      jobs: 2`
      
This configuration doesn't work if you don't enable KMS/Encryption on your minio. It would be nice to configure these settings.
For exemple, we need to change the AES256 to "" for backup and wal archiving to work.

**Comment by itay-grudev** [comment]
Am I correct in assuming that all you are asking for is that the settings are exposed in `.Values`?

**Comment by itay-grudev** [comment]
@donch Would #221 do the trick?
