### ISSUE TITLE
Add support for declarative role management

### ISSUE THREAD

**Issue by mrpotato3** [cloudnative-pg/charts#201]
Currently, the cluster does not allow assigning the "managed" section to manage user roles and credentials, as indicated in: 

https://cloudnative-pg.io/documentation/1.22/declarative_role_management/

**Comment by itay-grudev** [comment]
We'd accept PRs for this. Refer to [`CONTRIBUTING.md`](https://github.com/cloudnative-pg/charts/blob/main/CONTRIBUTING.md).

**Comment by gpothier** [comment]
Hi, I created this PR: https://github.com/cloudnative-pg/charts/pull/226

**Comment by gpothier** [comment]
I replaced the previous PR by PR #247
