### ISSUE TITLE
Feature Request: Adding postgresUID & postgresGID

### ISSUE THREAD

**Issue by NigelVanHattum** [cloudnative-pg/charts#206]
The [Clusterspec](https://cloudnative-pg.io/documentation/1.22/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec) contains the option to specify the used user/ group ID's for the database cluster.

The Helm template is missing these options.

**Comment by NigelVanHattum** [comment]
@itay-grudev Could you make a release for this?

**Comment by itay-grudev** [comment]
@NigelVanHattum Yhea, I will, but I am waiting for one more PR to get approved. Worst case would be next Monday I suppose.

**Comment by NigelVanHattum** [comment]
@itay-grudev Which PR are you waiting on, maybe I can help?
