### ISSUE TITLE
Grafana Dashboard - add WAL count

### ISSUE THREAD

**Issue by pchovelon** [cloudnative-pg/charts#217]
It could be great to have the number of WAL in the pg_wal folder, regardless their state.

**Comment by gbartolini** [comment]
@pchovelon have you considered also some of the metrics below (taken from [here](https://cloudnative-pg.io/documentation/current/monitoring/#predefined-set-of-metrics)? Is there any other which can be relevant?

```
cnpg_collector_pg_wal{value="count"} 9
cnpg_collector_pg_wal{value="slots_max"} NaN
cnpg_collector_pg_wal{value="keep"} 32
cnpg_collector_pg_wal{value="max"} 64
cnpg_collector_pg_wal{value="min"} 5
cnpg_collector_pg_wal{value="size"} 1.50994944e+08
cnpg_collector_pg_wal{value="volume_max"} 128
cnpg_collector_pg_wal{value="volume_size"} 2.147483648e+09
```

**Comment by pchovelon** [comment]
No I didn't, I think only the "count" is missing.
For the usage of the WAL volume I thought the panel "Volume Space Usage: PGDATA and WAL" already gives us this information.

**Comment by itay-grudev** [comment]
The panel was added to the dashboard in https://github.com/cloudnative-pg/grafana-dashboards. When #225 is merged, the updated version will also apply to the helm chart, so I'm closing this.
