### ISSUE TITLE
Single instance and PDB

### ISSUE THREAD

**Issue by gitarns** [cloudnative-pg/charts#233]
Hello,

When we create a single instance "Cluster", the operator adds a pdb with a minimum pod of one, making the pg pod immune to eviction.

Is there a configuration to disable the creation of the pdb ?

**Comment by itay-grudev** [comment]
Not as far as I am aware. This is a design feature of the operator to ensure that at least one database pod is always available, including during maintenance windows and node drains.

See: https://cloudnative-pg.io/documentation/current/operator_capability_levels/#maintenance-window-and-poddisruptionbudget-for-kubernetes-nodes
