### ISSUE TITLE
[Feature] Add nodeSelector to support cluster pods distribution among node group instances

### ISSUE THREAD

**Issue by samialitop3** [cloudnative-pg/charts#248]
When deploying to k8s cluster with a node group that has instances, there should be support for selecting the node group that the cluster pods will be deployed to, to make sure the pods are deployed on the desired instances for HA.

**Comment by itay-grudev** [comment]
Can you not achieve this by adding `affinity` rules to your cluster configuration?

See the CNPG [`Scheduling`](https://cloudnative-pg.io/documentation/current/scheduling/#pod-affinity-and-anti-affinity) documentation.

**Comment by samialitop3** [comment]
I can use `affinity` but here is the catch, I have more than one node group, so the cluster will be scheduling to other node groups in case I am doing replacement for the current node group that I want to the database cluster to be working on.

**Comment by itay-grudev** [comment]
The `cluster.affinity` is proxied to `ClusterSpec.AffinityConfiguration`. There you have the ability to set `nodeSelector` as well.
