### ISSUE TITLE
Helm chart support dual stuck clusters

### ISSUE THREAD

**Issue by M0NsTeRRR** [cloudnative-pg/charts#249]
There is no way for me to set the ipFamilyPolicy to "preferDualStack" in the current helm chart

**Comment by CoreFloDev** [comment]
OK so I was able to by pass the fact that they haven't merged the change by doing the change on my own version. However, I can't figure out how to fix it for the *-rw, *-ro and *-r service. Did you managed to fix that part? It is the same issue where it defaults to SingleStack for it ip family policy

**Comment by M0NsTeRRR** [comment]
Hello,
No this fix only apply to the helm chart services, regarding database service it must be added in the go code controller and I didn't have time to look into in.
