### ISSUE TITLE
How to create user with username and password for cluster?

### ISSUE THREAD

**Issue by abhithetfpl** [cloudnative-pg/charts#275]
I want to create user with username and password when I add helm charts in my helm chart as dependencies.

**Comment by itay-grudev** [comment]
The way I've done it before was:

```yaml
cluster:
  initdb:
    postInitSQL:
      - CREATE USER "username" WITH PASSWORD 'password';

**Comment by kastl-ars** [comment]
Sorry to chime in, but is there a more "GitOps" way of doing this?

Using the snipped above the user and password end up in the helm values file used to deploy the chart, i.e. they might be commited to a GitOps repository for e.g. ArgoCD or Flux.

Is there a way to specify a secret that contains the user credentials? So the secret could be created out-of-band or via SOPS or sealed-secrets?

**Comment by kastl-ars** [comment]
Answering myself:
If I understand the documentation on [bootstrapping](https://cloudnative-pg.io/documentation/1.23/bootstrap/) correctly, the following snipped should work:

```
cluster:
  initdb:
    database: app
    owner: app
    secret:
      name: app-secret
```

Not sure if this works via the chart, I'll try to test this...

**Comment by itay-grudev** [comment]
I brought a related question up in the last developer meeting. [Here](https://youtu.be/lGV7BMEc_9U?si=qN_MDfJ4rAs_dK1j&t=1341) @jsilvela suggests that the operator will respond to password secret changes transparently. Hence you can create sealed secrets, and you also can use Hashicorp Vault to manage them.

See: [Database Role Management](https://cloudnative-pg.io/documentation/current/declarative_role_management/)
See also: https://github.com/cloudnative-pg/charts/blob/50666bd57f8a63b8b28eeca70ab2c0b2404ab1c4/charts/cluster/values.yaml#L152-L163

**Comment by itay-grudev** [comment]
@kastl-ars If you have an idea on how to manage users better, I am open to integrating something like that into the chart.

**Comment by kastl-ars** [comment]
> Answering myself: If I understand the documentation on [bootstrapping](https://cloudnative-pg.io/documentation/1.23/bootstrap/) correctly, the following snipped should work:
> 
> ```
> cluster:
>   initdb:
>     database: app
>     owner: app
>     secret:
>       name: app-secret
> ```
> 
> Not sure if this works via the chart, I'll try to test this...

I have successfully tested this approach and it works. This way the credentials do not end up in the GitOps repository.

**Comment by kastl-ars** [comment]
> https://github.com/cloudnative-pg/charts/blob/50666bd57f8a63b8b28eeca70ab2c0b2404ab1c4/charts/cluster/values.yaml#L152-L163

Thanks for the reply and the links. The `values.yaml` unfortunately leaves out the example given in the documentation that you linked, in the `Password management` section.

```
  managed:
    roles:
    - name: dante
      ensure: present
      [… snipped …]
      passwordSecret:
        name: cluster-example-dante
```

I think it would be a good idea to add this to the values.yaml, to make it easier to find...
