### ISSUE TITLE
Add support for declarative shared_preload_libraries

### ISSUE THREAD

**Issue by mrpotato3** [cloudnative-pg/charts#278]
Currently, the cluster does not allow assigning the 'shared_preload_libraries' section to manage libraries other than timescaledb:

https://github.com/cloudnative-pg/charts/blob/9c668bcd2b00f1f820cfbe7bb76f4b8865a7dcfd/charts/cluster/templates/cluster.yaml#L51

**Comment by itay-grudev** [comment]
I think this is where I want to draw the line. The cluster chart is not indented to be a proxy for all possible parameters.

I believe that a CloudNativePG cluster is already relatively easy to set up manually if you understand the cluster architecture. The objective of the chart is to lower the entry barrier even further with sane defaults and some abstractions. I think this falls into that category.

I would advice you to set up a cluster resource manually if you need custom `shared_preload_libraries`.

Refer to the operator [documentation](https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/) for details.

**Comment by itay-grudev** [comment]
One last note, I wouldn't mind providing another template, such as the `timescaledb` we already provide. If that's the case, consider submitting a PR.
