### ISSUE TITLE
Crashloop on 0.14.1

### ISSUE THREAD

**Issue by rlex** [cloudnative-pg/charts#28]
Hello
Helm chart version: 0.14.1 crashes with following error:

Uses following image: ghcr.io/cloudnative-pg/cloudnative-pg:1.16.1

```
Error: unknown flag: --enable-leader-election
```

**Comment by sxd** [comment]
Hi @rlex 

This should be fixed in the latest release 0.14.2, please try

Regards!

**Comment by rlex** [comment]
Yep, works fine now, thanks!
