### ISSUE TITLE
Chart versioning "latest point release"

### ISSUE THREAD

**Issue by mindthecap** [cloudnative-pg/charts#282]
Hello!

Please clarify what it means that the operator chart is supporting "only the latest point release of the CloudNativePG operator". I see that the chart repository contains multiple chart versions.

**Comment by itay-grudev** [comment]
It means that when a new version of the chart is released, it's using the latest version of the operator available at the time. You cannot use the latest version of the chart, but select an older version of the operator. You'll have to use an older version of the chart. Refer to the `appVersion` field in the `Chart.yaml`.
