### ISSUE TITLE
feat(cluster): Create a Kyverno Chainsaw test suite

### ISSUE THREAD

**Issue by itay-grudev** [cloudnative-pg/charts#294]
To allow for more rapid development, increased reliability and easier reviews we need to add a test suite for the cluster chart and all of it's modes of operation.

KUTTL seems like an apropriate technology for the task, although I suspect there are a log of issues to be ironed out.

**Comment by phisco** [comment]
I've heard kuttl is kind of not really maintained, have a look at kyverno chainsaw maybe
