### ISSUE TITLE
No cnpg_* metrics in Prometheus, CloudNativePG Grafana Dashboard shows "no data"

### ISSUE THREAD

**Issue by rwarford** [cloudnative-pg/charts#302]
# Description of the issue
I have installed the Prometheus operator and CloudNativePG operator via ArgoCD but am not getting any _cnpg_*_ metrics in Prometheus.

Prometheus chart: **kube-prometheus-stack, revision 58.7.2**
CloudNativePG chart: **cloudnative-pg, revision 0.21.2**

# What Happens:

- The Grafana CloudNativePG dashboard shows "no data" for all controls.  
- Typing "cnpg" into the Prometheus UI doesn't match any metrics. ("cnpg_pg_replication_streaming_replicas" returns "empty query result, for example).
- Prometheus shows the target **podMonitor/cnpg-system/cnpg-cloudnative-pg/0** as up.
- The query _{job="cnpg-system/cnpg-cloudnative-pg"}_ does return data in Prometheus (such as _controller_runtime_active_workers records_).

# What I Expect
I expect the CloudNativePG Grafana dashboard to be correctly populated and I expect to be able to browse cnpg metrics in the Prometheus UI.

# What I've Tried

- I used the values recommend here: https://github.com/cloudnative-pg/charts/issues/279#issuecomment-2130308807
- I've tried installing downrev versions of both charts but it didn't help.

# Configuration Data
Prometheus cnpg podMonitor job configuration:
```
- job_name: podMonitor/cnpg-system/cnpg-cloudnative-pg/0
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    separator: ;
    regex: (Failed|Succeeded)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance, __meta_kubernetes_pod_labelpresent_app_kubernetes_io_instance]
    separator: ;
    regex: (cnpg);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_labelpresent_app_kubernetes_io_name]
    separator: ;
    regex: (cloudnative-pg);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: cnpg-system/cnpg-cloudnative-pg
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: metrics
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - cnpg-system```

**Comment by rwarford** [comment]
> `kube-prometheus-stack` by default only scrapes monitors that are labeled with it's release name. You can remove that behavior by setting:
> 
> ```yaml
> prometheus:
>   prometheusSpec:
>     podMonitorSelectorNilUsesHelmValues: false
>     ruleSelectorNilUsesHelmValues: false
>     serviceMonitorSelectorNilUsesHelmValues: false
>     probeSelectorNilUsesHelmValues: false
> ```
> 
> Alternatively you can apply the required labels to the CNPG resources, but the former solution is better when having a centralized cluster monitoring.
> 
> In any way, verify that the corresponding CNPG `ServiceMonitor`/`PodMonitor` resources exist. If they do, look for problems on the Prometheus side.

Thank you for your reply but please note that I pointed out in the "What I've Tried" section that **I used those settings and am still not getting any metrics**.  Also note that the cpng podMonitor _is_ recognized by Prometheus.

**Comment by rwarford** [comment]
@itay-grudev Could you take another look at this issue please?  As I mentioned in the comment above I did have the options set that you recommended.  I've added my PrometheusSpec to the original post.

I haven't done anything significant to the values files other than enable ingresses.  I do get other metrics in Prometheus (node metrics for example).

**Comment by itay-grudev** [comment]
From our perspective, the chart's responsibility ends at provisioning the appropriate resources. Debugging why the provisioned resources fail to be recognized by Prometheus falls outside of the assistance we have the capacity or will to provide.

That being said if you discover a genuine corner case that we haven't covered, feel free to open a new ticket.
