### ISSUE TITLE
[Question] What is the relationship between the cluster chart version and postgres/postgis versions?

### ISSUE THREAD

**Issue by Nils98Ar** [cloudnative-pg/charts#336]
Seems that the postgres image tag has the major.minor and postgis only major format.

How are new versions of the images translated into new cluster chart versions?

Or is it a better idea set the imageName incl. tag via value manually and update the chart and the image separately?

**Comment by itay-grudev** [comment]
There is a [PR (#306)](https://github.com/cloudnative-pg/charts/pull/306) that adds support for Postgis and allows you to specify the version you want. It does that by pulling the respective Postgis image from the [`postgis-containers`](https://github.com/cloudnative-pg/postgis-containers) repo.

Currently you can simply specify the Docker image you want to use.
