### ISSUE TITLE
Inplement option to set EnablePDB

### ISSUE THREAD

**Issue by emagiz** [cloudnative-pg/charts#395]
According to https://github.com/cloudnative-pg/cloudnative-pg/pull/3837/files#diff-67160e3b67586b511da3b6f279d73402e5bc70d9303786ddfda34aa99daae330R79, you can now set `EnablePDB` on the `Cluster` object to enable or disable PDB generation. This repository does not allow to set this yet, making it very difficult to perform maintanance. Specifically, the comments on https://github.com/cloudnative-pg/cloudnative-pg/issues/2570 are reasons to enable this in the chart.

**Comment by cterence** [comment]
Up on this issue please, ArgoCD now reports PDB as a degraded resource if it has 0 allowed disruptions (https://github.com/argoproj/argo-cd/issues/20171).
