### ISSUE TITLE
Consider moving the cloudnative-pg helm chart to cloudnative-pg repo

### ISSUE THREAD

**Issue by onedr0p** [cloudnative-pg/charts#42]
Hi 👋🏼 

It would be nice if the helm chart for cloudnative-pg could be moved to the https://github.com/cloudnative-pg/cloudnative-pg repo. One major issue with having this separate from the main repo is that the versions are not the same and that makes automation a bit tricky when managing CRDs outside the helm release.

![Alt Text](https://media.giphy.com/media/SVL5Dws0bOSgE/giphy.gif)

Kyverno is a pretty good example to showcase what I mean. In the following kustomization I can apply the CRDs and the Flux `HelmRelease` (with `.Values.installCRDs=false`) under the same Flux Kustomization and use renovate to manage the dependencies since the application and helm chart are in the same repo.

https://github.com/onedr0p/home-ops/blob/20f8533085c9a5ac8f07b46ba4a419caa2b60dc7/cluster/apps/kube-tools/kyverno/kustomization.yaml

When renovate discovers a new version of Kyverno you can see that a pull request is opened that can apply the CRDs and the `HelmRelease` in one shot.

https://github.com/onedr0p/home-ops/pull/4028/files 

Now you might ask, why do you need to separate the CRDs from the `HelmRelease`, why not just use `.Values.crds.create=true` ?

This is because kustomize will not be able to apply the CRDs generated from the Flux `HelmRelease` **before** the cnpg `Cluster` CR. Meaning the CRDs are not created before the cnpg `Cluster` CR tries to get created.

Given the helm chart was moved into the https://github.com/cloudnative-pg/cloudnative-pg repo I could make this all work very similar to how I have it working with Kyverno or kube-prometheus-stack since the raw CRDs would be under the same tag as the helm chart and the application. 

I know this is probably a longshot of a request but this is pretty much the only project I've ever come across where the developers who are both in control of the application and chart are using different repos and versions for each. It's a bit out of the norm when comparing to other popular projects like Kyverno, cert-manager, longhorn, rook-ceph, longhorn, trivy-operator and others I've come across where the developers are also in control of the helm chart and application.

Thanks

**Comment by onedr0p** [comment]
This was kind of brought up here.

https://github.com/cloudnative-pg/charts/issues/15#issuecomment-1184602591

**Comment by gbartolini** [comment]
(sorry for the late response, but I had not noticed this message earlier - probably because of the reason why you created this issue in the first place :P )
Would you be willing to help?

**Comment by phisco** [comment]
Hi, any particular reason not to use plain manifests directly, @onedr0p?

**Comment by onedr0p** [comment]
Do you mean this manifest?

https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.18.0/cnpg-1.18.0.yaml

If so, that's not a very convenient method because it would require kustomization patches and if anything I target or patched changed it would make it hard to update. Helm lends itself to only setting overrides for particular settings.

**Comment by onedr0p** [comment]
I'll go ahead and close this issue, the reason for me asking for this is no longer something I need.
