### ISSUE TITLE
Installing as a subchart fails on the second installation because of hardcoded webhook name

### ISSUE THREAD

**Issue by heruan** [cloudnative-pg/charts#443]
Having CNPG as a subchart, i.e.
```yaml
dependencies:
  - name: cloudnative-pg
    version: ~0.22.0
    repository: https://cloudnative-pg.github.io/charts
```

if fails with this error when installing the chart a second time with a different release name:

```
$ helm install foo ./umbrella-chart -ns foo
$ helm install bar ./umbrella-chart -ns bar

Error: INSTALLATION FAILED: Unable to continue with install: MutatingWebhookConfiguration "cnpg-mutating-webhook-configuration"
in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error:
key "meta.helm.sh/release-name" must equal "bar": current value is "foo"; annotation validation error:
key "meta.helm.sh/release-namespace" must equal "bar": current value is "foo"
```

This would be fixed if the name of the webhook would be prefixed by the release name instead of being hardcoded in https://github.com/cloudnative-pg/charts/blob/238f826c51f48318af9162f0dc1f54d99bbf07fa/charts/cloudnative-pg/templates/mutatingwebhookconfiguration.yaml#L18-L21

as it happens for example for [CertManager webhooks](https://github.com/cert-manager/cert-manager/blob/e5d62ad77501c2d429a7c1db5752a52604609016/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml#L4).

**Comment by heruan** [comment]
Same for the validating webhook: https://github.com/cloudnative-pg/charts/blob/238f826c51f48318af9162f0dc1f54d99bbf07fa/charts/cloudnative-pg/templates/validatingwebhookconfiguration.yaml#L18-L21

**Comment by itay-grudev** [comment]
You are not supposed to have two installations of the operator. You only need one operator per Kubernetes cluster. Even with the recent addition of namespace restricted installations, we don't support installing multiple operators.

I'd advise that you rework your infrastructure code to set up all the necessary operators required by your cluster before you install you application payload.

Including operators as part of the payload charts is a bad practice as they usually affect the whole cluster.
