### ISSUE TITLE
Support Multi Operator Scenarios

### ISSUE THREAD

**Issue by m4s-b3n** [cloudnative-pg/charts#460]
With v0.22.1 the possibility of limiting the operator to a single namespace using `config.clusterWide` was introduced. 

While this enables for single namespace deployment it is still not possible to deploy the operator to multiple namespaces as the webhooks names are hardcoded and webhooks can not be shared.

**Comment by itay-grudev** [comment]
This is a limitation of the operator, not the charts. I'd suggest raising the issue in https://github.com/cloudnative-pg/cloudnative-pg/, although I am pretty sure they are aware.

**Comment by m4s-b3n** [comment]
ok thx for getting back 😄

**Comment by afgane** [comment]
Given that `config.clusterWide` option exists, is there a working example somewhere that can be referenced? 

I'm running into the webhook naming issue when trying to install the chart multiple times in separate namespaces so wondering if there's a path forward?

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: MutatingWebhookConfiguration "cnpg-mutating-webhook-configuration" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata
```

**Comment by itay-grudev** [comment]
This was discussed during the Developer Meeting on Feb 19, 2025 ([#55](https://youtu.be/ITh5-gC5T5E)), where it was firmly decided against supporting multiple operator installations.

While this is possible with good knowledge of the operator and namespaced admission webhooks, it is a potentially unstable setup which the CloudNativePG team doesn't want to support.
