### ISSUE TITLE
Add helm chart for the Cluster CR

### ISSUE THREAD

**Issue by onedr0p** [cloudnative-pg/charts#50]
It would be nice if we could configure the Cluster (and possibly the ScheduledBackup) CRs with a helm chart.

**Comment by phisco** [comment]
Hi @onedr0p, I do understand the need, but it would just become a thin wrapper around the CRD, it would end up getting a few parameters for names and labels and then a complete Cluster spec we would transparently inject into the resource. I think helm charts should be more opinionated than that or at least add some more logic to be worth maintaining. What do you think? What's stopping you from creating your own helm chart for a Cluster with all and only the knobs you care about?

**Comment by onedr0p** [comment]
I'll go ahead and close this issue, the reason for me asking for this is no longer something I need.
